### ISSUE TITLE
Jig and logging

### ISSUE THREAD

**Issue by michaelklishin** [juxt/jig#13]
When I run a bunch of components via Jig in the REPL, I can't for the life of mine get `println` to print out anything.

Is there a public API for writing to Jig log? `clojure.tools.logging` doesn't seem to be available even though Jig is a dependency in my project.clj.

**Comment by malcolmsparks** [comment]
Normally, printlns appear in the REPL or the console (standard out) depending on whether the println is executed on the REPL thread or not. Projects under Jig can use clojure.tools.logging (info, infof, etc.) and by default, logback is used as the backend. The configuration is in Jig's resources/logback.xml.

It may be because you are depending on Jig from the project, which seems to work for some things but not for others (e.g. I've noticed the Jig console doesn't appear). I have more work to do to support configurations where the project depends on Jig, rather than the other way around. I'd like to keep the later so that Jig retains [internal programmability](http://martinfowler.com/bliki/InternalReprogrammability.html)

**Comment by michaelklishin** [comment]
I run Jig directly. In any case, I consider my question answered :)
