### ISSUE TITLE
Netty 5 alpha dependency in jig.netty

### ISSUE THREAD

**Issue by michaelklishin** [juxt/jig#15]
I see that `jig.netty` depends on Netty 5 alpha. Is this intentional? What does jig.netty do? Can we go back to `4.0.x` for the time being?

**Comment by malcolmsparks** [comment]
jig.netty provides the Server component, which bootstraps the Netty listeners. If you're not using it, remove jig.netty as a dependency. At the time, I decided to use an up-to-date Netty, since I didn't know if and when people would use this at all. My understanding is that there isn't much difference between 4.0.x and 5.

**Comment by michaelklishin** [comment]
There are fairly significant API changes in Netty 5. However, lets keep it at 5.

**Comment by malcolmsparks** [comment]
That could account for the need to change the major version number, but if memory serves the actual implementation is solid (it's not a speculative rewrite). But if there's anything we want to bring in which doesn't support v5 we should downgrade - I was simply being lazy here, hoping to save the work for an upgrade to v5 sometime in the future. Please feel free to downgrade to v4 though, if/when you need to.
